### PR TITLE
Run multiple models in parallel with multiple SDAs 

### PR DESCRIPTION
**Pull request by loctxmoreh**
`moreh-parallel-run.sh`: take a list of `timm` models, evenly distribute them to run on multiple SDAs, leveraging the existing `run_batch.sh`

### CODE REVIEW

**Comment by loctxmoreh** [comment]
Initial assumption: 
* All 5 SDAs are added and available
* Haven't handle SDA size
* Haven't handle the case of too few models

**Comment by loctxmoreh** [comment]
Still a WIP but you can check out the branch and try it out @yeomni

**Comment by loctxmoreh** [comment]
@huonglarne is not on the list of reviewers so i cannot request her for review...

**Review by huonglarne — APPROVED** [review]
I test ran the file and it seems to work fine.
I have some suggestions for future PRs:
- write a README with instructions to run and an example models list so that unfamiliar people can run quickly
- since the code run in parallel, the terminal log looks a bit chaotic. maybe there's a way to fix that

**Pull request merged**
