### PR TITLE
Add test MLFlow API

### PR DESCRIPTION
**Pull request by yeomni**
Applied MLFlow to `timm`.

confirmed to work fine.

Ref: https://www.notion.so/How-to-apply-MLFlow-da14a82b2fe349f388a0c30b7ce4f781

### CODE REVIEW

**Review by kimmorehvn — APPROVED** [review]
codes added for MLFlow pretty neat huh. Do we have a fixed 'formula' (set of code) to be added into every training loop?

**Comment by loctxmoreh** [comment]
I encounter this error while running the training script with `mlflow`:

```
Traceback (most recent call last):
  File "train.py", line 1106, in <module>
    main()
  File "train.py", line 805, in main
    eval_metrics = validate(
  File "train.py", line 1093, in validate
    mlflow.log_metric('acc@1', top1_m.val)
  File "/home/ubuntu/loctx/.conda/envs/timm/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 694, in log_metric
    MlflowClient().log_metric(run_id, key, value, get_current_time_millis(), step or 0)
  File "/home/ubuntu/loctx/.conda/envs/timm/lib/python3.8/site-packages/mlflow/tracking/client.py", line 749, in log_metric
    self._tracking_client.log_metric(run_id, key, value, timestamp, step)
  File "/home/ubuntu/loctx/.conda/envs/timm/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 288, in log_metric
    self.store.log_metric(run_id, metric)
  File "/home/ubuntu/loctx/.conda/envs/timm/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 199, in log_metric
    self._call_endpoint(LogMetric, req_body)
  File "/home/ubuntu/loctx/.conda/envs/timm/lib/python3.8/site-packages/mlflow/store/tracking/rest_store.py", line 59, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
  File "/home/ubuntu/loctx/.conda/envs/timm/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 201, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/ubuntu/loctx/.conda/envs/timm/lib/python3.8/site-packages/mlflow/utils/rest_utils.py", line 133, in verify_rest_response
    raise RestException(json.loads(response.text))
mlflow.exceptions.RestException: INVALID_PARAMETER_VALUE: Invalid metric name: 'acc@1'. Names may only contain alphanumerics, underscores (_), dashes (-), periods (.), spaces ( ), and slashes (/).
```

This should be simple to fix, tho

**Comment by loctxmoreh** [comment]
Also, this requires us to start the `mlflow` server on `127.0.0.1:5000` *before* starting the training script. I thinks it should be automatically started for us

**Comment by yeomni** [comment]
Additional commits are pushed. Please review again. Thanks!

**Comment by loctxmoreh** [comment]
@yeomni i suggest changes from [this PR](https://github.com/moreh-dev/pytorch-image-models/pull/4). Please check it out. I'd like to merge that PR before merging this one.

**Review by loctxmoreh — APPROVED** [review]

**Pull request merged**
